export interface AsmaName {
  id: number;
  nameAr: string;
  name: string;
  meaning: string;
  description: string;
}

export const asmaAllah: AsmaName[] = [
  { id: 1, nameAr: 'الله', name: 'Allah', meaning: 'Le Nom Suprême', description: 'Le Nom propre de Dieu, qui englobe tous Ses attributs de perfection.' },
  { id: 2, nameAr: 'الرحمن', name: 'Ar-Rahman', meaning: 'Le Tout Miséricordieux', description: 'Celui dont la miséricorde englobe toute la création.' },
  { id: 3, nameAr: 'الرحيم', name: 'Ar-Rahim', meaning: 'Le Très Miséricordieux', description: 'Celui qui accorde Sa miséricorde particulière aux croyants.' },
  { id: 4, nameAr: 'الملك', name: 'Al-Malik', meaning: 'Le Roi Souverain', description: 'Le Souverain absolu de toute la création.' },
  { id: 5, nameAr: 'القدوس', name: 'Al-Quddus', meaning: 'Le Pur, le Saint', description: 'Celui qui est exempt de toute imperfection.' },
  { id: 6, nameAr: 'السلام', name: 'As-Salam', meaning: 'La Paix, la Source de la paix', description: 'Celui qui est la source de toute paix et sécurité.' },
  { id: 7, nameAr: 'المؤمن', name: 'Al-Mu\'min', meaning: 'Le Garant de la foi', description: 'Celui qui accorde la sécurité et confirme la vérité.' },
  { id: 8, nameAr: 'المهيمن', name: 'Al-Muhaymin', meaning: 'Le Protecteur', description: 'Celui qui veille sur toute chose et la protège.' },
  { id: 9, nameAr: 'العزيز', name: 'Al-Aziz', meaning: 'Le Tout-Puissant', description: 'Celui dont la puissance est invincible.' },
  { id: 10, nameAr: 'الجبار', name: 'Al-Jabbar', meaning: 'Le Contraignant', description: 'Celui qui répare et restaure toute chose par Sa volonté.' },
  { id: 11, nameAr: 'المتكبر', name: 'Al-Mutakabbir', meaning: 'Le Superbe', description: 'Celui à qui appartient la grandeur absolue.' },
  { id: 12, nameAr: 'الخالق', name: 'Al-Khaliq', meaning: 'Le Créateur', description: 'Celui qui crée toute chose à partir du néant.' },
  { id: 13, nameAr: 'البارئ', name: 'Al-Bari\'', meaning: 'Le Créateur sans modèle préalable', description: 'Celui qui donne à chaque créature sa forme propre.' },
  { id: 14, nameAr: 'المصور', name: 'Al-Musawwir', meaning: 'Le Formateur', description: 'Celui qui façonne chaque créature de manière unique.' },
  { id: 15, nameAr: 'الغفار', name: 'Al-Ghaffar', meaning: 'Le Grand Pardonneur', description: 'Celui qui pardonne les péchés à répétition.' },
  { id: 16, nameAr: 'القهار', name: 'Al-Qahhar', meaning: 'Le Dominateur suprême', description: 'Celui qui subjugue toute chose par Sa puissance.' },
  { id: 17, nameAr: 'الوهاب', name: 'Al-Wahhab', meaning: 'Le Grand Donateur', description: 'Celui qui donne sans compter et sans attendre de retour.' },
  { id: 18, nameAr: 'الرزاق', name: 'Ar-Razzaq', meaning: 'Le Grand Pourvoyeur', description: 'Celui qui accorde la subsistance à toute créature.' },
  { id: 19, nameAr: 'الفتاح', name: 'Al-Fattah', meaning: 'Celui qui ouvre les portes', description: 'Celui qui ouvre les voies du bien et juge entre les hommes.' },
  { id: 20, nameAr: 'العليم', name: 'Al-Alim', meaning: 'L\'Omniscient', description: 'Celui dont la science embrasse toute chose.' },
  { id: 21, nameAr: 'القابض', name: 'Al-Qabid', meaning: 'Celui qui restreint', description: 'Celui qui resserre la subsistance selon Sa sagesse.' },
  { id: 22, nameAr: 'الباسط', name: 'Al-Basit', meaning: 'Celui qui étend', description: 'Celui qui élargit la subsistance selon Sa sagesse.' },
  { id: 23, nameAr: 'الخافض', name: 'Al-Khafid', meaning: 'Celui qui abaisse', description: 'Celui qui abaisse les orgueilleux et les tyrans.' },
  { id: 24, nameAr: 'الرافع', name: 'Ar-Rafi\'', meaning: 'Celui qui élève', description: 'Celui qui élève en rang qui Il veut.' },
  { id: 25, nameAr: 'المعز', name: 'Al-Mu\'izz', meaning: 'Celui qui honore', description: 'Celui qui accorde la puissance et l\'honneur.' },
  { id: 26, nameAr: 'المذل', name: 'Al-Mudhill', meaning: 'Celui qui humilie', description: 'Celui qui abaisse qui Il veut par Sa justice.' },
  { id: 27, nameAr: 'السميع', name: 'As-Sami\'', meaning: 'L\'Audient', description: 'Celui qui entend tout, même les pensées les plus secrètes.' },
  { id: 28, nameAr: 'البصير', name: 'Al-Basir', meaning: 'Le Clairvoyant', description: 'Celui qui voit toute chose, apparente ou cachée.' },
  { id: 29, nameAr: 'الحكم', name: 'Al-Hakam', meaning: 'L\'Arbitre suprême', description: 'Celui qui juge avec une justice parfaite.' },
  { id: 30, nameAr: 'العدل', name: 'Al-Adl', meaning: 'Le Juste', description: 'Celui dont la justice est absolue et sans faille.' },
  { id: 31, nameAr: 'اللطيف', name: 'Al-Latif', meaning: 'Le Tout Subtil', description: 'Celui qui connaît les détails les plus infimes avec douceur.' },
  { id: 32, nameAr: 'الخبير', name: 'Al-Khabir', meaning: 'Le Bien-Informé', description: 'Celui qui connaît la réalité profonde de toute chose.' },
  { id: 33, nameAr: 'الحليم', name: 'Al-Halim', meaning: 'Le Longanime', description: 'Celui qui fait preuve de patience et de clémence.' },
  { id: 34, nameAr: 'العظيم', name: 'Al-Azim', meaning: 'L\'Immense', description: 'Celui dont la grandeur dépasse toute description.' },
  { id: 35, nameAr: 'الغفور', name: 'Al-Ghafur', meaning: 'Le Pardonneur', description: 'Celui qui couvre les péchés et pardonne largement.' },
  { id: 36, nameAr: 'الشكور', name: 'Ash-Shakur', meaning: 'Le Reconnaissant', description: 'Celui qui récompense généreusement les bonnes actions.' },
  { id: 37, nameAr: 'العلي', name: 'Al-Ali', meaning: 'Le Très-Haut', description: 'Celui dont le rang est au-dessus de toute chose.' },
  { id: 38, nameAr: 'الكبير', name: 'Al-Kabir', meaning: 'Le Très Grand', description: 'Celui dont la grandeur surpasse toute chose créée.' },
  { id: 39, nameAr: 'الحفيظ', name: 'Al-Hafiz', meaning: 'Le Gardien', description: 'Celui qui préserve toute chose de la disparition.' },
  { id: 40, nameAr: 'المقيت', name: 'Al-Muqit', meaning: 'Le Nourricier', description: 'Celui qui pourvoit à la subsistance de chaque être.' },
  { id: 41, nameAr: 'الحسيب', name: 'Al-Hasib', meaning: 'Celui qui suffit', description: 'Celui qui suffit à Ses serviteurs et tient les comptes.' },
  { id: 42, nameAr: 'الجليل', name: 'Al-Jalil', meaning: 'Le Majestueux', description: 'Celui à qui appartient la majesté absolue.' },
  { id: 43, nameAr: 'الكريم', name: 'Al-Karim', meaning: 'Le Généreux', description: 'Celui dont la générosité est sans limite.' },
  { id: 44, nameAr: 'الرقيب', name: 'Ar-Raqib', meaning: 'L\'Observateur', description: 'Celui qui surveille toute chose sans relâche.' },
  { id: 45, nameAr: 'المجيب', name: 'Al-Mujib', meaning: 'Celui qui répond', description: 'Celui qui répond aux invocations de Ses serviteurs.' },
  { id: 46, nameAr: 'الواسع', name: 'Al-Wasi\'', meaning: 'L\'Immense, le Vaste', description: 'Celui dont la miséricorde et la science embrassent tout.' },
  { id: 47, nameAr: 'الحكيم', name: 'Al-Hakim', meaning: 'Le Sage', description: 'Celui dont chaque décret est empreint de sagesse parfaite.' },
  { id: 48, nameAr: 'الودود', name: 'Al-Wadud', meaning: 'L\'Affectueux', description: 'Celui qui aime Ses serviteurs pieux et est aimé d\'eux.' },
  { id: 49, nameAr: 'المجيد', name: 'Al-Majid', meaning: 'Le Glorieux', description: 'Celui dont la gloire et la noblesse sont infinies.' },
  { id: 50, nameAr: 'الباعث', name: 'Al-Ba\'ith', meaning: 'Celui qui ressuscite', description: 'Celui qui ressuscitera les morts au Jour du Jugement.' },
  { id: 51, nameAr: 'الشهيد', name: 'Ash-Shahid', meaning: 'Le Témoin', description: 'Celui qui est témoin de toute chose, en tout temps et lieu.' },
  { id: 52, nameAr: 'الحق', name: 'Al-Haqq', meaning: 'La Vérité absolue', description: 'Celui dont l\'existence et la parole sont la vérité même.' },
  { id: 53, nameAr: 'الوكيل', name: 'Al-Wakil', meaning: 'Le Garant', description: 'Celui à qui l\'on peut confier toute affaire.' },
  { id: 54, nameAr: 'القوي', name: 'Al-Qawiyy', meaning: 'Le Fort', description: 'Celui dont la force est absolue et sans faiblesse.' },
  { id: 55, nameAr: 'المتين', name: 'Al-Matin', meaning: 'L\'Inébranlable', description: 'Celui dont la puissance est ferme et constante.' },
  { id: 56, nameAr: 'الولي', name: 'Al-Wali', meaning: 'Le Protecteur', description: 'Celui qui protège et prend en charge Ses serviteurs.' },
  { id: 57, nameAr: 'الحميد', name: 'Al-Hamid', meaning: 'Le Digne de louange', description: 'Celui qui mérite toute louange en toute circonstance.' },
  { id: 58, nameAr: 'المحصي', name: 'Al-Muhsi', meaning: 'Celui qui dénombre', description: 'Celui qui connaît le nombre exact de toute chose.' },
  { id: 59, nameAr: 'المبدئ', name: 'Al-Mubdi\'', meaning: 'L\'Initiateur', description: 'Celui qui a créé toute chose la première fois.' },
  { id: 60, nameAr: 'المعيد', name: 'Al-Mu\'id', meaning: 'Celui qui restaure', description: 'Celui qui ressuscitera la création après sa disparition.' },
  { id: 61, nameAr: 'المحيي', name: 'Al-Muhyi', meaning: 'Celui qui donne la vie', description: 'Celui qui insuffle la vie à toute chose.' },
  { id: 62, nameAr: 'المميت', name: 'Al-Mumit', meaning: 'Celui qui donne la mort', description: 'Celui qui met fin à la vie de toute créature.' },
  { id: 63, nameAr: 'الحي', name: 'Al-Hayy', meaning: 'Le Vivant', description: 'Celui dont la vie est éternelle et parfaite.' },
  { id: 64, nameAr: 'القيوم', name: 'Al-Qayyum', meaning: 'Celui qui subsiste par Lui-même', description: 'Celui qui n\'a besoin de rien et dont tout dépend.' },
  { id: 65, nameAr: 'الواجد', name: 'Al-Wajid', meaning: 'Celui qui trouve', description: 'Celui qui ne manque de rien et trouve tout ce qu\'Il veut.' },
  { id: 66, nameAr: 'الماجد', name: 'Al-Majid', meaning: 'Le Noble', description: 'Celui dont la noblesse et la générosité sont infinies.' },
  { id: 67, nameAr: 'الواحد', name: 'Al-Wahid', meaning: 'L\'Unique', description: 'Celui qui est unique dans Son essence et Ses attributs.' },
  { id: 68, nameAr: 'الصمد', name: 'As-Samad', meaning: 'L\'Absolu', description: 'Celui dont tous les êtres ont besoin, alors qu\'Il ne dépend de personne.' },
  { id: 69, nameAr: 'القادر', name: 'Al-Qadir', meaning: 'Le Tout-Puissant', description: 'Celui qui a le pouvoir absolu sur toute chose.' },
  { id: 70, nameAr: 'المقتدر', name: 'Al-Muqtadir', meaning: 'Le Déterminant', description: 'Celui dont la puissance domine et détermine toute chose.' },
  { id: 71, nameAr: 'المقدم', name: 'Al-Muqaddim', meaning: 'Celui qui avance', description: 'Celui qui place qui Il veut en avant.' },
  { id: 72, nameAr: 'المؤخر', name: 'Al-Mu\'akhkhir', meaning: 'Celui qui retarde', description: 'Celui qui place qui Il veut en arrière.' },
  { id: 73, nameAr: 'الأول', name: 'Al-Awwal', meaning: 'Le Premier', description: 'Celui qui existe avant toute chose, sans commencement.' },
  { id: 74, nameAr: 'الآخر', name: 'Al-Akhir', meaning: 'Le Dernier', description: 'Celui qui existera après toute chose, sans fin.' },
  { id: 75, nameAr: 'الظاهر', name: 'Az-Zahir', meaning: 'L\'Apparent', description: 'Celui dont l\'existence est manifeste par Ses signes.' },
  { id: 76, nameAr: 'الباطن', name: 'Al-Batin', meaning: 'Le Caché', description: 'Celui dont l\'essence est inaccessible aux sens.' },
  { id: 77, nameAr: 'الوالي', name: 'Al-Wali', meaning: 'Le Gouverneur', description: 'Celui qui gère et administre toute la création.' },
  { id: 78, nameAr: 'المتعالي', name: 'Al-Muta\'ali', meaning: 'Le Très-Élevé', description: 'Celui qui est élevé au-dessus de toute imperfection.' },
  { id: 79, nameAr: 'البر', name: 'Al-Barr', meaning: 'Le Bienfaisant', description: 'Celui dont la bonté envers Ses créatures est immense.' },
  { id: 80, nameAr: 'التواب', name: 'At-Tawwab', meaning: 'Celui qui accepte le repentir', description: 'Celui qui accueille sans cesse le repentir de Ses serviteurs.' },
  { id: 81, nameAr: 'المنتقم', name: 'Al-Muntaqim', meaning: 'Le Vengeur', description: 'Celui qui punit les injustes avec justice.' },
  { id: 82, nameAr: 'العفو', name: 'Al-Afuww', meaning: 'Celui qui efface les fautes', description: 'Celui qui efface les péchés comme s\'ils n\'avaient jamais existé.' },
  { id: 83, nameAr: 'الرؤوف', name: 'Ar-Ra\'uf', meaning: 'Le Compatissant', description: 'Celui dont la douceur et la bonté sont sans limite.' },
  { id: 84, nameAr: 'مالك الملك', name: 'Malik al-Mulk', meaning: 'Le Souverain du Royaume', description: 'Celui à qui appartient la royauté absolue de l\'univers.' },
  { id: 85, nameAr: 'ذو الجلال والإكرام', name: 'Dhul-Jalali wal-Ikram', meaning: 'Le Maître de la Majesté et de la Générosité', description: 'Celui qui réunit la majesté suprême et la générosité infinie.' },
  { id: 86, nameAr: 'المقسط', name: 'Al-Muqsit', meaning: 'L\'Équitable', description: 'Celui qui établit la justice parfaite entre Ses créatures.' },
  { id: 87, nameAr: 'الجامع', name: 'Al-Jami\'', meaning: 'Le Rassembleur', description: 'Celui qui rassemblera toutes les créatures au Jour du Jugement.' },
  { id: 88, nameAr: 'الغني', name: 'Al-Ghaniyy', meaning: 'Le Riche par excellence', description: 'Celui qui n\'a besoin de rien ni de personne.' },
  { id: 89, nameAr: 'المغني', name: 'Al-Mughni', meaning: 'Celui qui enrichit', description: 'Celui qui accorde richesse et suffisance à qui Il veut.' },
  { id: 90, nameAr: 'المانع', name: 'Al-Mani\'', meaning: 'Celui qui empêche', description: 'Celui qui protège Ses serviteurs des maux qu\'Il repousse.' },
  { id: 91, nameAr: 'الضار', name: 'Ad-Darr', meaning: 'Celui qui inflige le mal', description: 'Celui qui, dans Sa sagesse, permet l\'épreuve.' },
  { id: 92, nameAr: 'النافع', name: 'An-Nafi\'', meaning: 'Celui qui est utile', description: 'Celui qui accorde le bien et le bénéfice à Ses créatures.' },
  { id: 93, nameAr: 'النور', name: 'An-Nur', meaning: 'La Lumière', description: 'Celui qui illumine les cieux, la terre et les cœurs.' },
  { id: 94, nameAr: 'الهادي', name: 'Al-Hadi', meaning: 'Le Guide', description: 'Celui qui guide vers le droit chemin qui Il veut.' },
  { id: 95, nameAr: 'البديع', name: 'Al-Badi\'', meaning: 'Le Créateur incomparable', description: 'Celui qui crée sans modèle préexistant.' },
  { id: 96, nameAr: 'الباقي', name: 'Al-Baqi', meaning: 'L\'Éternel', description: 'Celui dont l\'existence perdure sans fin ni disparition.' },
  { id: 97, nameAr: 'الوارث', name: 'Al-Warith', meaning: 'L\'Héritier', description: 'Celui à qui reviendra tout après la disparition de la création.' },
  { id: 98, nameAr: 'الرشيد', name: 'Ar-Rashid', meaning: 'Le Guide droit', description: 'Celui qui mène toute chose à sa juste fin avec sagesse.' },
  { id: 99, nameAr: 'الصبور', name: 'As-Sabur', meaning: 'Le Très Patient', description: 'Celui qui fait preuve d\'une patience infinie envers Ses créatures.' },
];
